### ISSUE TITLE
Check Valid Pointer

### ISSUE THREAD

**Issue by adspro15** [JustasMasiulis/nt_wrapper#17]
It would be great if you added pointer check.
Thx

**Comment by JustasMasiulis** [comment]
Could you elaborate more on the matter?

However I'd like to note that it is not in the spirit of the project to add any sort of argument validity checks. Debug assert would be the most I'd add in that department.

**Comment by adspro15** [comment]
many people have trouble checking pointers without delay and winapi
I would like to see it in your performance
This is just sentence of nothing more.

**Comment by JustasMasiulis** [comment]
There are only 2 ways that I am aware of to check whether a pointer is "valid" in usermode: 

- `NtQueryVirtualMemory/VirtualQuery` which is prone to cause a race in multithreaded applications.
- Catching the exception if the pointer is invalid using SEH which may not be available in certain cases. 

So there isn't really anything to add to boost the performance.

**Comment by JustasMasiulis** [comment]
I don't have any further solutions so I'll close the issue.
