### ISSUE TITLE
Process Creation

### ISSUE THREAD

**Issue by iIIusi0n** [JustasMasiulis/nt_wrapper#29]
Is there process creating feature?

I can't find code for it.

**Comment by JustasMasiulis** [comment]
I have some code personally, but it's not exactly compatible with what `ntw` currently is.

Could you elaborate what exactly do you need? Because it could be completely trivial or require thousands of lines of code.

**Comment by JustasMasiulis** [comment]
I have some code personally, but it's not exactly compatible with what `ntw` currently is.

Could you elaborate what exactly do you need? Because it could be completely trivial or require thousands of lines of code.

**Comment by iIIusi0n** [comment]
I need simple example for NtCreateUserProcess. There is some example about it in the internet but every code is broken. I tried to fix it and successfully create suspended process, but when i resume it, it terminated with access violation. (checked from windbg)

**Comment by JustasMasiulis** [comment]
you can try using this as a reference https://github.com/x64dbg/TitanEngine/blob/8d93135f382acd9317dc37d248c4499b091ac419/TitanEngine/TitanEngine.Debugger.cpp#L302

**Comment by iIIusi0n** [comment]
Thank you. Maybe it is what i wanted. I will check it :)

**Comment by iIIusi0n** [comment]
![code-snapshot](https://user-images.githubusercontent.com/56464250/120726638-83219a00-c513-11eb-8be4-8f51148dac9b.png)

Ref that u told me is really helpful. And i succeed to create process with suspended state. But when i resume it - using NtResumeThread or ProcessHacker - it crashed. My parameter was wrong?

Edit: Its working perfectly! (- 1%)
Putty - Working
Calc - Working
Cmd - Working
Notepad - Crash (lol)

Thank you for good advice and ref.

**Comment by Soledge** [comment]
If you don't mind me asking, Which parameter was wrong? I'm trying to reproduce this and i'm having troubles with crashes, as i followed your sample verbatim.
